### ISSUE TITLE
handle broken GSL API between versions >1.16 and <2.3

### ISSUE THREAD

**Issue by timflutre** [xqwen/IRLS#5]
The IRLS library is used by the [eQtlBma](https://github.com/timflutre/eqtlbma) package, for which [this issue](https://github.com/timflutre/eqtlbma/issues/22) was raised. I managed to solve it for the eQtlBma specific part. I am now doing the same for IRLS. More info later.

**Comment by timflutre** [comment]
My current code is in branch "fix_issue5", but a very strange thing happens.

Currently, Ubuntu 16.04 (the current LTS) ships GSL version 2.1. However, the multiple linear regression API was broken at that time (see details [here](http://lists.gnu.org/archive/html/help-gsl/2016-10/msg00003.html)), and then restored in v2.3. It hence is necessary to deal with that smoothly. That's what I did with [this](https://github.com/xqwen/IRLS/commit/899d94e8b38b5c168d3f4f895fedf13a57262075) commit, basically:

```
#if GSL_MAJOR_VERSION == 1 && GSL_MINOR_VERSION < 17
    gsl_multifit_wlinear_svd(X, w, z, GSL_DBL_EPSILON, &rank, bv, cov, &chisq, work);
#elif GSL_MAJOR_VERSION == 2 && GSL_MINOR_VERSION > 2
    gsl_multifit_wlinear(X, w, z, Bhat, covBhat, &rss, work);
    (*rank) = gsl_multifit_linear_rank(GSL_DBL_EPSILON, work);
#else
    fprintf(stderr,
            "ERROR: your GSL is %s, but should be <= 1.16 or >= 2.3\n",
            gsl_version);
    exit(EXIT_FAILURE);
#endif
```

To check that it's working, I installed GSL 1.16 and 2.3 in a custom location, in $HOME. Then, I had to modify a few things in IRLS, notably in the Makefile. And in the end, I am now able to easily compile with the GSL version I want (easy to check with `ldd`), and then to run the tests. And there, surprisingly, I see this error message:

```
ERROR: your GSL is 2.3, but should be <= 1.16 or >= 2.3
```
(same for GSL v1.16)

So I don't have a clue about what is going on...

**Comment by szcf-weiya** [comment]
@timflutre I also encountered a similar problem. My computer is also Ubuntu 16.04, and gsl-2.1 has been installed. But after I install gsl-2.3 from source, although `gsl-config --version` return 2.3, the code on your branch still return  
`ERROR: your GSL is 2.3, but should be <= 1.16 or >= 2.3`
Then I use `ldd test_irls` to check the ld path. I found that these share libraries point to `/usr/lib/x86_64-linux-gnu/`, which I think belongs to gsl-2.1, NOT gsl-2.3. So I deleted these share libraries, and export the shared libraries search path of gsl-2.3 (for me, it is `/usr/local/lib`) to LD_LIBRARY_PATH.

**Comment by szcf-weiya** [comment]
@timflutre  
In the following code, there might some typos need to fix

`
#elif GSL_MAJOR_VERSION == 2 && GSL_MINOR_VERSION > 2
    gsl_multifit_wlinear(X, w, z, Bhat, covBhat, &rss, work);
    (*rank) = gsl_multifit_linear_rank(GSL_DBL_EPSILON, work);
`

Firstly, `Bhat`, `covBhat` and `rss` have not been defined; and `*rank` should be `rank`, so the above code should be

`
#elif GSL_MAJOR_VERSION == 2 && GSL_MINOR_VERSION > 2
    gsl_multifit_wlinear(X, w, z, bv, cov, &chisq, work);
    rank = gsl_multifit_linear_rank(GSL_DBL_EPSILON, work);
`

**Comment by timflutre** [comment]
Thanks @szcf-weiya for spotting the typos! I corrected them.

I also added `-I/path/to/include` to `CXXFLAGS` and, I don't know why, but this time the execution with the proper GSL worked...

So can you check if branch `fix_issue5` works for you, too?

**Comment by szcf-weiya** [comment]
@timflutre I just checked the branch `fix_issue5`, it works for my PC.

**Comment by timflutre** [comment]
ok, perfect, I will see with @xqwen , but I think we can merge it into the `master` branch

**Comment by timflutre** [comment]
I got no answer from @xqwen after several months, so I decided to merge the "fix_issue5" branch into "master.
